# syntax=docker/dockerfile:1

############################
# 1. Base stage
############################
FROM ubuntu:24.04 AS base

LABEL maintainer="Atsushi TAKEDA @takedarts"

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /opt/prod

# Install build dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        git make g++ wget ca-certificates \
        python3.12 python3.12-dev python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install python modules
RUN pip3 install --no-cache-dir --break-system-packages \
        cython cmake numpy \
    && pip3 install --no-cache-dir --break-system-packages \
        torch --index-url https://download.pytorch.org/whl/cpu

############################
# 2. Build stage
############################
FROM base AS builder

# Clone the repository and build the project
ARG BRANCH=main
RUN git clone --branch ${BRANCH} --depth=1 https://github.com/takedarts/maru . \
    && python3 src/build.py \
    && rm -rf src/deepshogi/native/build

############################
# 3. Runtime stage
############################
FROM ubuntu:24.04 AS runtime

WORKDIR /opt/prod

# Install build dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3.12 python3-pip libpython3.12t64 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install python modules
RUN pip3 install --no-cache-dir --break-system-packages \
        numpy \
    && pip3 install --no-cache-dir --break-system-packages \
        torch --index-url https://download.pytorch.org/whl/cpu

# Copy the built project from the builder stage
COPY --from=builder /opt/prod /opt/prod

# Copy the run script
COPY --chmod=755 run.sh /opt/run.sh

WORKDIR /workspace

# Set the default command to display help
CMD ["/opt/run.sh", "--help"]
